#!/bin/bash

openssl req -x509 \
    -nodes \
    -days 365 \
    -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=example.com"

if [ $? -ne 0 ]
then
    bash
else
    service nginx start

    if [ $? -ne 0 ]
    then
        bash
    else
        cd /usr/local/src/comagic_web/comagic/
        ../.venv/bin/python runserver.py
    fi
fi
