#!/bin/bash

workspaceDir=/usr/local/src
projectName=utils

function changeOwner {
    if [ ! -d $workspaceDir/$1 ]
    then
        if [ -n $COMAGIC_ENV_USER ]
        then
            chown -R $COMAGIC_ENV_USER:$COMAGIC_ENV_USER $workspaceDir/$1
        fi
    fi
}

if [ ! -d $workspaceDir/$projectName ]
then
    cd $workspaceDir/
    git clone git@github.com:aoanshakov/$projectName.git
    changeOwner $projectName
fi

proxyDir=utils/amocrm-proxy
fullPathToProxyDir=$workspaceDir/$proxyDir

if [ -d $fullPathToProxyDir/.venv ]
then
    exit 0
fi

cd $fullPathToProxyDir
python3 -m venv .venv
.venv/bin/pip3 install flask requests
changeOwner $proxyDir
