#!/bin/bash

cd ~/.vim/plugin

# Clone nvim-cmp
git clone https://github.com/hrsh7th/nvim-cmp.git

# Clone cmp-nvim-lsp
git clone https://github.com/hrsh7th/cmp-nvim-lsp.git

# Clone LuaSnip
git clone https://github.com/L3MON4D3/LuaSnip.git

# Clone cmp_luasnip
git clone https://github.com/saadparwaiz1/cmp_luasnip.git
