#!/bin/bash

path=/usr/local/src

if [ ! -d $path ]
then
    echo "директория приложения смонтирована некорректно"
    exit 1
fi

export SIP_LIB_TEST_USER=""
action="server"

while [ -n "$1" ]
do
    if [ "$1" = "--owner" ]
    then
        export SIP_LIB_TEST_USER=$2
        shift
    fi

    shift
done

cd $path

openssl req -x509 \
    -nodes \
    -days 365 \
    -newkey rsa:2048 \
    -keyout /etc/ssl/private/nginx-selfsigned.key \
    -out /etc/ssl/certs/nginx-selfsigned.crt \
    -subj "/C=GB/ST=London/L=London/O=Global Security/OU=IT Department/CN=example.com"

service nginx start
bash
