#!/bin/bash

path=/usr/local/src/admin_frontend

cd $path

if [ ! -d $path/node_modules ]
then
    cd $path
    npm install
    fix-permissions $path
fi

if [ ! -d $path/build ]
then
    build
fi

path=/usr/local/src/tests

cd $path

if [ ! -d $path/node_modules ]
then
    cd $path
    npm install
    fix-permissions $path
fi

