#!/bin/bash

srcDir=/usr/local/src
comagicWebDir=$srcDir/comagic_web

cd $srcDir

if [ ! -d $comagicWebDir ]
then
    git clone git@git.dev.uis.st:web/comagic_web.git
    cd comagic_web
fi

if [ ! -d $HOME/.pip ]
then
    mkdir $HOME/.pip
fi

if [ ! -d $comagicWebDir/.venv/bin ]
then
    cd $comagicWebDir

    chmod +x venv.sh
    cp /home/pip.conf $HOME/.pip/pip.conf

    patch -p1 < /home/requirements.txt.diff

    ./venv.sh <<< "y"

    chmod -x venv.sh
    rm $HOME/.pip/pip.conf
    .venv/bin/pip install --upgrade Wand numpy

    patch -p1 -R < /home/requirements.txt.diff
fi

if [ ! -d $comagicWebDir/node_modules ]
then
    npm install
    rm package-lock.json
fi

if [ -n $COMAGIC_ENV_USER ]
then
    chown -R $COMAGIC_ENV_USER:$COMAGIC_ENV_USER /usr/local/src/comagic_web/
fi
