#!/bin/bash

cd /usr/local/src

git clone git@git.dev.uis.st:web/comagic_web.git
cd comagic_web

if [ ! -d $HOME/.pip ]
then
    mkdir $HOME/.pip
fi

chmod +x venv.sh
cp /home/pip.conf $HOME/.pip/pip.conf

patch -p1 < /home/requirements.txt.diff

./venv.sh <<< "y"

chmod -x venv.sh
rm $HOME/.pip/pip.conf
.venv/bin/pip install --upgrade Wand numpy

npm install
rm package-lock.json

if [ -n $COMAGIC_ENV_USER ]
then
    chown -R $COMAGIC_ENV_USER:$COMAGIC_ENV_USER /usr/local/src/comagic_web/
fi

patch -p1 -R < /home/requirements.txt.diff
