#!/bin/bash

path=/usr/local/src/admin_frontend
script='build'

while [ -n "$1" ]
do
    if [ "$1" = "--watch" ]
    then
        script='start'
        shift
    fi

    shift
done

utils --action modify-code

cd $path
npm run $script
fix-permissions $path
