#!/bin/bash

path=/usr/local/src

if [ ! -d $path ]
then
    echo "директория приложения смонтирована некорректно"
    exit 1
fi

export SIP_LIB_TEST_USER=""
action="server"

while [ -n "$1" ]
do
    if [ "$1" = "--owner" ]
    then
        export SIP_LIB_TEST_USER=$2
        shift
    elif [ "$1" = "--action" ]
    then
        action=$2
        shift
    fi

    shift
done

if [ $action = "initialize" ]
then
    initialize
elif [ $action = "server" ]
then
    initialize
    utils --action run-server
    bash
elif [ $action = "bash" ]
then
    initialize
    bash
fi
