#!/bin/bash

action="server"
workspace=""
port=""
farg=""
isOsX=0
dockerArguments=""
entrypointArguments=""
buildImage=0
noCache=""

if [ $(uname | grep Darwin | wc -l) -eq 0 ]
then
    dockerArguments="$dockerArguments --mount type=bind,source=/etc/passwd,target=/etc/passwd"
    dockerArguments="$dockerArguments --mount type=bind,source=/etc/group,target=/etc/group"
    entrypointArguments="$entrypointArguments --owner $USER"
    farg="-f"
else
    isOsX=1
fi

function getAbsolutePath {
    currentDirectory=$(pwd)
    cd $@
    result=$(pwd)
    echo $result
    cd $currentDirectory
}

function usageError {
    echo $@
    echo "Для того чтобы узнать как пользоваться скриптом запуска контейнера выполни команду \"$0 --help\""
}

while [ -n "$1" ]
do
    if [ "$1" = "--build-image" ]
    then
        buildImage=1
    elif [ "$1" = "--no-cache" ]
    then
        noCache="--no-cache"
    elif [ "$1" = "--port" ]
    then
        if [ -z "$2" ]
        then
            echo "Укажите номер порта, который будет соответстовать восьмидесятому порту в контейнере."
            exit 1
        fi

        dockerArguments="$dockerArguments -p $2:80"
        shift
    elif [ "$1" = "--action" ]
    then
        action=$2

        if [ -z $action ]
        then
            usageError "Укажи действие \"initialize\", \"server\", или \"bash\". "
            exit 1
        fi

        if [ "$action" != "initialize" ] && [ "$action" != "server" ] && [ "$action" != "bash" ]
        then
            usageError "Действие $action не поддерживается. Можно использовать только действия \"initialize\", " \
                "\"server\", или \"bash\". "
            exit 1
        fi

        shift
    elif [ "$1" = "--help" ] || [ "$1" = "-h" ]
    then
        echo "Для того чтобы запустить bash в контейнере выполни команду \"$0 --action bash\""
        echo "Для того чтобы запустить веб-приложение, выполни команду \"$0 --port 1234\" и открой URL " \
            "http://127.0.0.1:1234/index.html в Google Chrome."
        exit 0
    else
        usageError "Аргумент $1 не поддерживается. Скрипту могут быть переданы только опции --port, --action, " \
            "--no-cache, --build-image, или --server."
        exit 1
    fi

    shift
done

docker --version
if [ $? -ne 0 ]
then
    echo "Установи докер"
    exit 1
fi

currentFile=$0

if [ -L $currentFile ]
then
    currentFile=$(readlink $farg $currentFile)
    if [ $? -ne 0 ]
    then
        echo "Не удалось получить путь к скрипту"
        exit 1
    fi
fi

currentDir=$(dirname $currentFile)
if [ $? -ne 0 ]
then
    echo "Не удалось получить текущую директорию"
    exit 1
fi

imageTag='bitrix-widget'

if [ $buildImage -eq 1 ]
then
    docker build $noCache -t $imageTag $currentDir
    if [ $? -ne 0 ]
    then
        echo "Не удалось собрать образ"
        exit 1
    fi

    exit 0
fi

if [ -z "$workspace" ]
then
    if [ -n "$ADMIN_FRONTEND_TEST_WORKSPACE" ]
    then
        workspace=$ADMIN_FRONTEND_TEST_WORKSPACE
    fi
fi

if [ -n "$workspace" ]
then
    if [ ! -d $workspace ]
    then
        echo "Директория $workspace не существует"
        exit 1
    fi

    workspace="-v $workspace:/usr/local/src/admin_frontend"
fi

if [ -z "$workspace" ]
then
    echo "Путь к приложению не указан"
    exit 1
fi

linesCount=$(docker images ${imageTag} | wc -l)
if [ $? -ne 0 ]
then
    echo "Не удалось получить список образов"
    exit 1
fi

if [ $linesCount -eq 1 ]
then
    docker build --no-cache -t $imageTag $currentDir

    if [ $? -ne 0 ]
    then
        echo "Не удалось собрать образ"
        exit 1
    fi
fi

testsDir="$currentDir/.."

if [ $isOsX -eq 0 ]
then
    testsDir=$(readlink -f $testsDir)
    if [ $? -ne 0 ]
    then
        echo "Не удалось получить директорию с приложением"
        exit 1
    fi
else
    testsDir=$(getAbsolutePath $testsDir)
fi

docker run -it --rm \
    $workspace \
    -v $testsDir:/usr/local/src/tests \
    --mount type=bind,source=$HOME/.ssh/known_hosts,target=/root/.ssh/known_hosts \
    --mount type=bind,source=$HOME/.ssh/id_rsa,target=/root/.ssh/id_rsa \
    $dockerArguments \
    $imageTag \
    --action $action \
    $entrypointArguments
