#!/bin/bash

action="initialize"
applicationDirectory=""
farg=""
isOsX=0
dockerArguments=""
entrypointArguments=""
buildImage=0
noCache=""
imageTag="electron-builder"

if [ $(uname | grep Darwin | wc -l) -eq 0 ]
then
    dockerArguments="$dockerArguments --mount type=bind,source=/etc/passwd,target=/etc/passwd"
    dockerArguments="$dockerArguments --mount type=bind,source=/etc/group,target=/etc/group"
    dockerArguments="$dockerArguments --mount type=bind,source=$HOME/.ssh/id_ed25519,target=/root/.ssh/id_ed25519"
    entrypointArguments="$entrypointArguments --owner $USER"
    farg="-f"
else
    isOsX=1
    dockerArguments="$dockerArguments --mount type=bind,source=$HOME/.ssh/id_rsa,target=/root/.ssh/id_rsa"
fi

function getAbsolutePath {
    currentDirectory=$(pwd)
    cd $@
    result=$(pwd)
    echo $result
    cd $currentDirectory
}

while [ -n "$1" ]
do
    if [ "$1" = "--build-image" ]
    then
        buildImage=1
    elif [ "$1" = "--action" ]
    then
        action=$2
        shift
    elif [ "$1" = "--no-cache" ]
    then
        noCache="--no-cache"
    elif [ "$1" = "--port" ]
    then
        if [ -z "$2" ]
        then
            echo "Укажите номер порта, который будет соответстовать порту 443 в контейнере."
            exit 1
        fi

        dockerArguments="$dockerArguments -p $2:443"
        action="run-server"
        shift
    elif [ "$1" = "--network=host" ]
    then
        dockerArguments="$dockerArguments $1"
        shift
    else
        entrypointArguments="$entrypointArguments $1"
    fi

    shift
done

docker --version
if [ $? -ne 0 ]
then
    echo "Установи докер"
    exit 1
fi

currentFile=$0

if [ -L $currentFile ]
then
    currentFile=$(readlink $farg $currentFile)
    if [ $? -ne 0 ]
    then
        echo "Не удалось получить путь к скрипту"
        exit 1
    fi
fi

currentDirectory=$(dirname $currentFile)
if [ $? -ne 0 ]
then
    echo "Не удалось получить текущую директорию"
    exit 1
fi

if [ $isOsX -eq 0 ]
then
    currentDirectory=$(readlink -f $currentDirectory)
    if [ $? -ne 0 ]
    then
        echo "Не удалось получить директорию с приложением"
        exit 1
    fi
else
    currentDirectory=$(getAbsolutePath $currentDirectory)
fi

if [ $buildImage -eq 1 ]
then
    if [ $updater -eq 1 ]
    then
        sed -i '' 's/setup_14/setup_11/g' $buildDir/Dockerfile
    fi

    docker build $noCache -t $imageTag $currentDirectory

    if [ $? -ne 0 ]
    then
        echo "Не удалось собрать образ"
        exit 1
    fi

    exit 0
fi

linesCount=$(docker images ${imageTag} | wc -l)
if [ $? -ne 0 ]
then
    echo "Не удалось получить список образов"
    exit 1
fi

if [ $linesCount -eq 1 ]
then
    docker build --no-cache -t $imageTag $currentDirectory

    if [ $? -ne 0 ]
    then
        echo "Не удалось собрать образ"
        exit 1
    fi
fi

docker run -it --rm \
    -v $currentDirectory:/usr/local/src \
    --mount type=bind,source=$HOME/.ssh/known_hosts,target=/root/.ssh/known_hosts \
    --network=host \
    $dockerArguments \
    $imageTag \
    --action $action \
    $entrypointArguments
