#!/bin/bash

mode="--watch --test"
server=""
eventsws=""

if [ -n "$AMOCRM_WIDGET_SERVER_DOMAIN" ]
then
    server="--server $AMOCRM_WIDGET_SERVER_DOMAIN"
fi

if [ -n "$AMOCRM_WIDGET_EVENTS_WS_DOMAIN" ]
then
    eventsws="--eventsws $AMOCRM_WIDGET_EVENTS_WS_DOMAIN"
fi

while [ -n "$1" ]
do
    if [ "$1" = "--production" ]
    then
        mode=""
    fi

    shift
done

path=/usr/local/src/amocrm_widget
$path/node_modules/.bin/webpack --mode development --theme uis $server $eventsws $mode

if [ -n "$COMAGIC_ENV_USER" ]
then
    chown -R $COMAGIC_ENV_USER:$COMAGIC_ENV_USER $path 
fi
