#!/bin/bash

web_dir=/usr/local/src/amocrm-widget-web-root

if [ ! -d $web_dir ]
then
    mkdir $web_dir

    if [ -n $COMAGIC_ENV_USER ]
    then
        chown -R $COMAGIC_ENV_USER:$COMAGIC_ENV_USER $web_dir
    fi
fi

if [ ! -d /usr/local/src/utils ]
then
    cd /usr/local/src
    git clone git@github.com:aoanshakov/utils.git

    if [ -n $COMAGIC_ENV_USER ]
    then
        chown -R $COMAGIC_ENV_USER:$COMAGIC_ENV_USER /usr/local/src/utils
    fi
fi

if [ ! -d /usr/local/src/amocrm_widget ]
then
    cd /usr/local/src
    git clone git@git.dev.uis.st:crm/amocrm_widget.git
    cd amocrm_widget
    npm install

    if [ -n $COMAGIC_ENV_USER ]
    then
        chown -R $COMAGIC_ENV_USER:$COMAGIC_ENV_USER /usr/local/src/amocrm_widget
    fi
fi
