#!/bin/bash

user=""
port=""
action="server"
widget_type="uis"

while [ -n "$1" ]
do
    if [ "$1" = "-p" ]
    then
        port="-p $2:80 "
        shift
    elif [ "$1" = "-t" ]
    then
        widget_type=$2
        shift
    elif [ "$1" = "-a" ]
    then
        action=$2
        shift
    elif [ "$1" = "-u" ]
    then
        user=$2
        shift
    fi

    shift
done

docker run -it --rm \
    -v $HOME/workspace:/usr/local/src \
    --mount type=bind,source=$HOME/.ssh/id_rsa,target=/root/.ssh/id_rsa \
    --mount type=bind,source=/etc/passwd,target=/etc/passwd \
    --mount type=bind,source=/etc/group,target=/etc/group \
    ${port}amocrm-tests -u $USER -t $widget_type -a $action
