#!/bin/bash 
#cd /home/anshakov/uis-description
#python generate-json.py /home/anshakov/amocrm_widget
rm -rf /home/anshakov/amocrm_deploy/*
cd /home/anshakov/amocrm_widget
grunt
unzip build/$1/widget.zip -d /home/anshakov/amocrm_deploy
cp /home/anshakov/uis-description/backbone-min.js /home/anshakov/amocrm_deploy/backbone.js
cp /home/anshakov/uis-description/underscore-min.js /home/anshakov/amocrm_deploy/underscore.js
cp /home/anshakov/twig.js/twig.min.js /home/anshakov/amocrm_deploy/
cp /home/anshakov/uis-description/templates.js /home/anshakov/amocrm_deploy/
cp /home/anshakov/JsSIP/dist/jssip.js /home/anshakov/amocrm_deploy/

cp /home/anshakov/utils/phone-widget/helpers.js /home/anshakov/amocrm_deploy/
cp /home/anshakov/utils/phone-widget/modal-window.js /home/anshakov/amocrm_deploy/
cp /home/anshakov/utils/phone-widget/promise-mock.js /home/anshakov/amocrm_deploy/
cp /home/anshakov/utils/phone-widget/promise-polyfill.js /home/anshakov/amocrm_deploy/

cp -r /home/anshakov/amocrm_lib/root/* /home/anshakov/amocrm_deploy/
cp /home/anshakov/amocrm_deploy/moment.min.js /home/anshakov/amocrm_deploy/moment.js
