#!/bin/bash

#code='uis_widget_9'
#key='c6fb51e48e7786dbffae4c943695bfcdaf08543fdd6275e70e8a292f4621a942'

code='uis_widget_10'
key='0a4f13fa532871f0171e578fb72f560055c4c724d806704c5a489532a040048f'

server='proxy.dev.uis.st:15016'

#eventsws='va.uiscom.ru'
#eventsws='amocrm2.comagic.ru'
eventsws='proxy.dev.uis.st:12021'
#eventsws='proxy.dev.uis.st:15015'
#eventsws='my2.comagic.ru'

sip-lib-test --action build --application amocrm-widget --code $code --key $key --server $server --eventsws $eventsws
