#!/bin/bash

port=''
action=''
server='myow1.dev.uis.st'

while [ -n "$1" ]
do
    if [ "$1" = "-p" ]
    then
        port="-p $2:443"
        shift
    elif [ "$1" = "-s" ]
    then
        server=$2
    else
        action=$1
    fi

    shift
done


docker run -it --rm \
    -v $HOME/workspace:/usr/local/src \
    $port \
    --mount type=bind,source=$HOME/.ssh/id_rsa,target=/root/.ssh/id_rsa \
    --mount type=bind,source=/etc/passwd,target=/etc/passwd \
    --mount type=bind,source=/etc/group,target=/etc/group \
    call-center-frontend -u $USER -s $server $action
