#!/bin/bash

port=""
action="runclient"

while [ -n "$1" ]
do
    if [ "$1" = "-p" ]
    then
        port="-p $2:8080"
        shift
    elif [ "$1" = "-a" ]
    then
        action=$2
        shift
    fi

    shift
done

docker run -it --rm \
    -v $HOME/gitlab.uis.dev/comagic_web:/usr/local/src/comagic_web \
    --mount type=bind,source=$HOME/gitlab.uis.dev/comagic-config.json,target=/usr/local/src/comagic-config.json \
    --mount type=bind,source=$HOME/.ssh/id_rsa,target=/root/.ssh/id_rsa \
    --mount type=bind,source=/etc/passwd,target=/etc/passwd \
    --mount type=bind,source=/etc/group,target=/etc/group \
    $port comagic-web -a $action -u $USER
