#!/bin/bash

port=""
action="runclient"
dockerArguments=""
entrypointArguments=""

while [ -n "$1" ]
do
    if [ "$1" = "-p" ] || [ "$1" = "--port" ]
    then
        port="-p $2:443"
        shift
    elif [ "$1" = "-a" ] || [ "$1" = "--action" ]
    then
        action=$2
        shift
    elif [ "$1" = "--network=host" ]
    then
        dockerArguments="$dockerArguments $1"
        shift
    fi

    shift
done

if [ $(uname | grep Darwin | wc -l) -eq 0 ]
then
    dockerArguments="$dockerArguments --mount type=bind,source=/etc/passwd,target=/etc/passwd"
    dockerArguments="$dockerArguments --mount type=bind,source=/etc/group,target=/etc/group"
    dockerArguments="$dockerArguments --mount type=bind,source=$HOME/.ssh/id_ed25519,target=/root/.ssh/id_ed25519"
    entrypointArguments="$entrypointArguments -u $USER"
else
    dockerArguments="$dockerArguments --mount type=bind,source=$HOME/.ssh/id_rsa,target=/root/.ssh/id_rsa"
fi


docker run -it --rm \
    -v $HOME/gitlab.uis.dev/comagic_web:/usr/local/src/comagic_web \
    -v $HOME/workspace/utils/docker/comagic-web/configure:/home/configure \
    --mount type=bind,source=$HOME/gitlab.uis.dev/comagic-config.json,target=/usr/local/src/comagic-config.json \
    $dockerArguments $port \
    comagic-web $entrypointArguments -a $action
