#!/bin/bash

port=""
action="runclient"
workspace="workspace"

while [ -n "$1" ]
do
    if [ "$1" = "-p" ]
    then
        port="-p $2:8080"
        shift
    elif [ "$1" = "-a" ]
    then
        action=$2
        shift
    elif [ "$1" = "-w" ]
    then
        workspace=$2
        shift
    fi

    shift
done

docker run -it --rm \
    -v $HOME/$workspace:/usr/local/src \
    --mount type=bind,source=$HOME/.ssh/id_rsa,target=/root/.ssh/id_rsa \
    --mount type=bind,source=/etc/passwd,target=/etc/passwd \
    --mount type=bind,source=/etc/group,target=/etc/group \
    $port comagic-web -a $action -u $USER
