const src = '/usr/local/src',
    application = `${src}/comagic_app`,
    nodeModules = `${application}/node_modules`,
    packageLockJson = `${application}/package-lock.json`,
    tests = `${src}/tests`,
    updater = `${tests}/updater`,
    utils = `${tests}/utils`,
    preCommitHook = `${application}/.husky/pre-commit`,
    misc = `${application}/misc`,
    softphoneMisc = `${misc}/softphone/misc`,
    analyticsDir = `${misc}/analytics`,
    analytics = `${analyticsDir}/frontend`,
    sipLib = `${softphoneMisc}/sip_lib`,
    sailsPgSession = `${tests}/sails_pg_session`,
    updaterConfig =`${updater}/config`,
    publisherDir = `${tests}/publisher`,
    softphone = `${misc}/softphone`,
    contacts = `${misc}/contacts`,
    chats = `${misc}/chats`;

module.exports = {
    application,
    tests,
    nodeModules,
    scheduler: `${nodeModules}/react-dom/node_modules/scheduler`,
    fileSaver: `${nodeModules}/file-saver`,
    broadcastChannel: `${nodeModules}/broadcast-channel`,
    webpackDevServer: `${nodeModules}/webpack-dev-server`,
    packageLockJson,
    nginxConfig: `${utils}/nginx.conf`,
    server: `${utils}/server.js`,
    testsServerLog: `${tests}/tests-server-log.log`,
    testsServerPid: `${tests}/tests-server.pid`,
    testsScriptsDir: `${tests}/tests`,
    preCommitHook,
    stub: `${tests}/Stub.js`,
    shadowContentTsxSource: `${tests}/ShadowContent.tsx`,
    shadowContentTsxTarget: `${analytics}/src/components/ShadowContent.tsx`,
    contactList: `${tests}/contact-list.js`,
    femaleNames: `${tests}/female-names`,
    maleNames: `${tests}/male-names`,
    fileSaverPatch: `${tests}/file-saver-patch.diff`,
    schedulerPatch: `${tests}/scheduler-patch.diff`,
    broadcastChannelPatch: `${tests}/broadcast-channel-patch.diff`,
    webpackDevServerPatch: `${tests}/webpack-dev-server-patch.diff`,
    applicationPatch: `${tests}/application-patch.diff`,
    devApplicationPatch: `${tests}/dev-application-patch.diff`,
    chatsPatch: `${tests}/chats-patch.diff`,
    corePatch: `${tests}/core-patch.diff`,
    magicUiPatch: `${tests}/magic-ui-patch.diff`,
    magicUiLibPatch: `${tests}/magic-ui-lib-patch.diff`,
    softphonePatch: `${tests}/softphone-patch.diff`,
    analyticsPatch: `${tests}/analytics-patch.diff`,
    contactsPatch: `${tests}/contacts-patch.diff`,
    devSoftphonePatch: `${tests}/dev-softphone-patch.diff`,
    sipLibPatch: `${tests}/sip-lib-patch.diff`,
    huskyPatch: `${tests}/husky-patch.diff`,
    updaterPatch: `${tests}/updater-patch.diff`,
    misc,
    magicUi: `${misc}/magic_ui`,
    chats,
    chatsMagicUi: `${chats}/magic_ui`,
    softphone,
    softphoneMagicUi: `${softphone}/magic_ui`,
    core: `${misc}/core`,
    analyticsDir,
    analytics,
    softphoneMisc,
    sipLib,
    uisWebRTC: `${sipLib}/uis_webrtc`,
    sipLibMagiUi: `${sipLib}/magic_ui`,
    updater,
    pgHbaConf: `${tests}/pg_hba.conf`,
    localJsSource: `${tests}/local.js`,
    localJsTarget: `${updaterConfig}/local.js`,
    sailsPgSession,
    sailsPgSessionSql: `${sailsPgSession}/sql/sails-pg-session-support.sql`,
    updaterLog: `${tests}/updater.log`,
    publisherDir,
    assets: `${tests}/assets`,
    publisher: `${publisherDir}/index.js`,
    contactsMagicUi: `${contacts}/magic_ui`,
    contacts
};
