#!/bin/bash

workspaceDir=/usr/local/src/

function changeOwner {
    if [ ! -d $workspaceDir/$1 ]
    then
        if [ -n $COMAGIC_ENV_USER ]
        then
            chown -R $COMAGIC_ENV_USER:$COMAGIC_ENV_USER $workspaceDir/$1
        fi
    fi
}

projectName=utils

if [ ! -d $workspaceDir/$projectName ]
then
    cd $workspaceDir/
    git clone git@github.com:aoanshakov/$projectName.git
    changeOwner $projectName
fi

testsDir=utils/call-center-tests
fullPathToTestsDir=$workspaceDir/$testsDir

if [ -d $fullPathToTestsDir/node_modules ]
then
    exit 0
fi

cd $fullPathToTestsDir
npm install
changeOwner $testsDir
